apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-with-limits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-with-limits
  template:
    metadata:
      labels:
        app: stress-with-limits
    spec:
      containers:
      - name: stress
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "300M", "--timeout", "300s"]

        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "256Mi"